name: php

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.1'
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-

      - name: Persist analyser caches
        id: analyser-cache
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-analyser-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-analyser-${{ matrix.php }}-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Analyse code
        run: composer analyse

      - name: Enable corepack for Yarn
        run: corepack enable yarn

      - name: Prepare Yarn projects for testing
        working-directory: tests/examples
        run: |
          pushd yarn-1.x && yarn && popd
          pushd yarn-2.4 && yarn && popd
          pushd yarn-3.5 && yarn && popd

      - name: Run tests
        run: composer test
